# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=50)),
                ('duracion', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tiempo_asignado', models.FloatField(default=0, null=True)),
                ('estado', models.CharField(choices=[(b'Pendiente', b'Pendiente'), (b'Ejecutando', b'Ejecutando'), (b'Cancelado', b'Cancelado'), (b'Finalizado', b'Finalizado')], max_length=50)),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint_Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default=b'', max_length=50)),
                ('sprint', models.CharField(default=b'', max_length=50)),
            ],
        ),
    ]
