# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fechaFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
    ]
