# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprints', '0002_auto_20160610_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
    ]
