# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprints', '0003_auto_20160610_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ejecutando', 'Ejecutando'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sprint_usuarios',
            name='sprint',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sprint_usuarios',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
