# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('captrabajo', models.IntegerField(default=0)),
                ('trabasignado', models.FloatField(default=0)),
                ('descripcion', models.CharField(default='', max_length=240)),
                ('es_administrador', models.BooleanField(default=False)),
                ('proyectos', models.ManyToManyField(default=None, to='proyectos.Proyecto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
