# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoUS', '0001_initial'),
        ('Sprints', '__first__'),
        ('proyectos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Flujos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('proyecto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto')),
                ('sprint', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Sprints.Sprint')),
                ('tipoUS', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tipoUS.tipo_us')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='flujo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flujos.Flujos'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
    ]
