# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flujos', '0001_initial'),
        ('tipoUS', '0001_initial'),
        ('usuario', '0001_initial'),
        ('Sprints', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUS', models.CharField(default='', max_length=50)),
                ('valor_negocio', models.FloatField(default=0)),
                ('valor_tecnico', models.FloatField(default=0)),
                ('prioridad_cliente', models.FloatField(default=0)),
                ('prioridad', models.FloatField(default=0)),
                ('tiempo_planificado', models.FloatField(default=0)),
                ('tiempo_ejecutado', models.FloatField(default=0)),
                ('tiempo_acumulado', models.FloatField(default=0)),
                ('descripcion_corta', models.CharField(default='', max_length=80)),
                ('descripcion_larga', models.TextField(default='', max_length=5000)),
                ('notas', models.TextField(default='', max_length=6000)),
                ('terminado', models.BooleanField(default=False)),
                ('estado', models.CharField(default='', max_length=100, null=True)),
                ('actividad', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flujos.Actividades')),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sprints.Sprint')),
                ('tipoUS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipoUS.tipo_us')),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.UserProfile')),
            ],
        ),
    ]
